# Generated by Django 5.0.4 on 2024-07-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Event_Tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='event',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='event',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='event',
            name='Image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
