# Generated by Django 5.0.4 on 2024-07-31 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_tickets_event_image1_event_image2_and_more'),
        ('login', '0009_testimonial_testimonial_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='discount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.profile'),
            preserve_default=False,
        ),
    ]
