# Generated by Django 5.0.7 on 2024-07-31 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_question_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option1',
            new_name='Option1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option2',
            new_name='Option2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option3',
            new_name='Option3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option4',
            new_name='Option4',
        ),
    ]
