# Generated by Django 5.0.4 on 2024-07-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_ticket_discount_ticket_email_ticket_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='price',
            new_name='total_paid_price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='ticket',
            name='tickets',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
