# Generated by Django 5.0.4 on 2024-07-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_price_ticket_total_paid_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
