# Generated by Django 5.0.7 on 2024-07-31 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_option1_question_option1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Option3',
            new_name='option3',
        ),
    ]
