# Generated by Django 5.0.7 on 2024-07-31 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_option3_question_option3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Option1',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Option2',
            new_name='option2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Option4',
            new_name='option4',
        ),
    ]
