# Generated by Django 5.0.4 on 2024-08-01 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_ticket_slug'),
        ('events', '0006_rename_option1_question_option1_and_more'),
    ]

    operations = [
    ]
