# Generated by Django 5.0.4 on 2024-08-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_merge_20240801_1113'),
    ]

    operations = [
       
    ]
