# Generated by Django 5.0.4 on 2024-08-01 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_ticket_id_ticket_ticket_id_alter_ticket_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='slug',
        ),
    ]
