# Generated by Django 5.0.4 on 2024-08-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_ticket_slug'),
    ]

    operations = [
        
        
    ]
