# Generated by Django 5.0.4 on 2024-08-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_ticket_ticket_id_ticket_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
