# Generated by Django 5.0.4 on 2024-08-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_ticket'),
    ]

    operations = [
        
        
    ]
