# Generated by Django 5.0.4 on 2024-08-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_rename_option1_question_a_rename_option2_question_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
