# Generated by Django 5.0.4 on 2024-08-03 16:44

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_question_quiz'),
        ('login', '0010_testimonial_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Image3',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Image4',
        ),
        migrations.AlterField(
            model_name='event',
            name='Image1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
       
    ]
