# Generated by Django 5.0.4 on 2024-08-03 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_remove_event_image2_remove_event_image3_and_more'),
        ('login', '0010_testimonial_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='image',
        )
    ]
