runtime: python39

env_variables:
  # Define your environment variables here
  DJANGO_SETTINGS_MODULE: wmcgta.settings

handlers:
  # Serve the static files directory
  - url: /static
    static_dir: staticfiles/

  # Serve the media files directory (for user-uploaded images)
  - url: /media
    static_dir: media/

  # Route all other requests to the Django application
  - url: /.*
    script: auto

entrypoint: uvicorn wmcgta.asgi:application --host 0.0.0.0 --port 8080
