# Generated by Django 5.0.6 on 2024-07-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.URLField()),
                ('KarmaPoints', models.IntegerField(default=0)),
                ('Account_Balance', models.IntegerField(default=0)),
                ('user_type', models.CharField(max_length=100)),
                ('Membership_license', models.CharField(max_length=100)),
                ('Total_Donation', models.IntegerField(default=0)),
            ],
        ),
    ]
