# Generated by Django 4.2.13 on 2024-07-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Membership_license',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default='User', max_length=100),
        ),
    ]
