# Generated by Django 4.2.13 on 2024-07-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_profile_mobile_alter_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='KarmaPoints',
            fields=[
                ('karma_points_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('karma_points', models.IntegerField(default=0)),
                ('karma_points_type', models.CharField(max_length=100)),
                ('reference_id', models.CharField(max_length=100)),
            ],
        ),
    ]
