# Generated by Django 4.2.13 on 2024-07-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_karmapoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('payee_id', models.CharField(max_length=100)),
                ('payer_id', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=100)),
                ('transaction_amount', models.IntegerField(default=0)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
