# Generated by Django 4.2.13 on 2024-07-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karmapoints',
            name='reference_id',
            field=models.CharField(default='No Reference', max_length=100),
        ),
    ]
