# Generated by Django 5.0.4 on 2024-07-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='Testimonial_topic',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
