# Generated by Django 4.2.13 on 2024-07-13 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('donation_amount', models.IntegerField(default=0)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('donation_category', models.CharField(max_length=100)),
                ('donation_description', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('Donatiers_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donation_STATS.donation')),
            ],
        ),
    ]
