# Generated by Django 4.2.13 on 2024-07-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_STATS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='Donatiers_name',
            new_name='Donaters_name',
        ),
    ]
