# Generated by Django 4.2.13 on 2024-07-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_STATS', '0003_remove_donation_slug_remove_donation_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Donation_STATS.statistics'),
        ),
    ]
