# Generated by Django 4.2.13 on 2024-07-13 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_STATS', '0004_donation_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donation_STATS.statistics'),
        ),
    ]
