# Generated by Django 4.2.13 on 2024-07-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_STATS', '0005_alter_donation_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='user_id',
            new_name='Donaters_UserID',
        ),
    ]
