# Generated by Django 4.2.13 on 2024-07-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_STATS', '0006_rename_user_id_donation_donaters_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
