# Generated by Django 4.2.13 on 2024-07-13 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Donation_STATS', '0007_delete_donation_delete_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donaters_UserID', models.CharField(default='unknown', max_length=100)),
                ('value', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('donation_amount', models.IntegerField(default=0)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('donation_category', models.CharField(max_length=100)),
                ('donation_description', models.CharField(max_length=100)),
                ('Donaters_UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donation_STATS.statistics')),
            ],
        ),
    ]
