# Generated by Django 4.2.13 on 2024-07-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_STATS', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='ranking',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
