# Generated by Django 4.2.13 on 2024-07-20 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_STATS', '0010_statistics_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='Donaters_UserID',
        ),
        migrations.AddField(
            model_name='donation',
            name='UserID',
            field=models.CharField(default='not available', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donation_STATS.statistics'),
        ),
    ]
