# Generated by Django 4.2.13 on 2024-07-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_STATS', '0011_remove_donation_donaters_userid_donation_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='value',
            field=models.PositiveBigIntegerField(),
        ),
    ]
